"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const orders_products_download_controllers_1 = require("../controllers/orders_products_download.controllers");
const router = (0, express_1.Router)();
router.route('/orders_products_download/getall/').get(orders_products_download_controllers_1.get_orders_products_download_all);
router.route('/orders_products_download/:id').get(orders_products_download_controllers_1.get_orders_products_download_byid);
router.route('/orders_products_download/create/').post(orders_products_download_controllers_1.port_orders_products_download);
router.route('/orders_products_download/put/').put(orders_products_download_controllers_1.put_orders_products_download);
router.route('/orders_products_download/del/').delete(orders_products_download_controllers_1.delete_orders_products_download);
exports.default = router;
