"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const whos_online_controllers_1 = require("../controllers/whos_online.controllers");
const router = (0, express_1.Router)();
router.route('/whos_online/getall/').get(whos_online_controllers_1.get_whos_online_all);
router.route('/whos_online/:id').get(whos_online_controllers_1.get_whos_online_byid);
router.route('/whos_online/create/').post(whos_online_controllers_1.port_whos_online);
router.route('/whos_online/put/').put(whos_online_controllers_1.put_whos_online);
router.route('/whos_online/del/').delete(whos_online_controllers_1.delete_whos_online);
exports.default = router;
