"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const currencies_controllers_1 = require("../controllers/currencies.controllers");
const router = (0, express_1.Router)();
router.route('/currencies/getall/').get(currencies_controllers_1.get_currencies_all);
router.route('/currencies/:id').get(currencies_controllers_1.get_currencies_byid);
router.route('/currencies/create/').post(currencies_controllers_1.port_currencies);
router.route('/currencies/put/').put(currencies_controllers_1.put_currencies);
router.route('/currencies/del/').delete(currencies_controllers_1.delete_currencies);
exports.default = router;
