"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const products_options_values_controllers_1 = require("../controllers/products_options_values.controllers");
const router = (0, express_1.Router)();
router.route('/products_options_values/getall/').get(products_options_values_controllers_1.get_products_options_values_all);
router.route('/products_options_values/:id').get(products_options_values_controllers_1.get_products_options_values_byid);
router.route('/products_options_values/create/').post(products_options_values_controllers_1.port_products_options_values);
router.route('/products_options_values/put/').put(products_options_values_controllers_1.put_products_options_values);
router.route('/products_options_values/del/').delete(products_options_values_controllers_1.delete_products_options_values);
exports.default = router;
