"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const zones_controllers_1 = require("../controllers/zones.controllers");
const router = (0, express_1.Router)();
router.route('/zones/getall/').get(zones_controllers_1.get_zones_all);
router.route('/zones/:id').get(zones_controllers_1.get_zones_byid);
router.route('/zones/create/').post(zones_controllers_1.port_zones);
router.route('/zones/put/').put(zones_controllers_1.put_zones);
router.route('/zones/del/').delete(zones_controllers_1.delete_zones);
exports.default = router;
