"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const address_book_controllers_1 = require("../controllers/address_book.controllers");
const router = (0, express_1.Router)();
router.route('/address_book/getall/').get(address_book_controllers_1.get_address_book_all);
router.route('/address_book/:id').get(address_book_controllers_1.get_address_book_byid);
router.route('/address_book/customer/:id').get(address_book_controllers_1.get_address_book_bycustomerId);
router.route('/address_book/create/').post(address_book_controllers_1.port_address_book);
router.route('/address_book/put/').put(address_book_controllers_1.put_address_book);
router.route('/address_book/del/').delete(address_book_controllers_1.delete_address_book);
exports.default = router;
