"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const app = (0, express_1.default)();
const index_routes_1 = __importDefault(require("./routes/index.routes"));
const a_routers_1 = __importDefault(require("./routes/a.routers"));
const address_book_routers_1 = __importDefault(require("./routes/address_book.routers"));
const address_format_routers_1 = __importDefault(require("./routes/address_format.routers"));
const administrators_routers_1 = __importDefault(require("./routes/administrators.routers"));
const banners_routers_1 = __importDefault(require("./routes/banners.routers"));
const banners_history_routers_1 = __importDefault(require("./routes/banners_history.routers"));
const categories_routers_1 = __importDefault(require("./routes/categories.routers"));
const categories_description_routers_1 = __importDefault(require("./routes/categories_description.routers"));
const configuration_routers_1 = __importDefault(require("./routes/configuration.routers"));
const configuration_group_routers_1 = __importDefault(require("./routes/configuration_group.routers"));
const counter_routers_1 = __importDefault(require("./routes/counter.routers"));
const counter_history_routers_1 = __importDefault(require("./routes/counter_history.routers"));
const countries_routers_1 = __importDefault(require("./routes/countries.routers"));
const currencies_routers_1 = __importDefault(require("./routes/currencies.routers"));
const customers_routers_1 = __importDefault(require("./routes/customers.routers"));
const customers_basket_routers_1 = __importDefault(require("./routes/customers_basket.routers"));
const customers_basket_attributes_routers_1 = __importDefault(require("./routes/customers_basket_attributes.routers"));
const customers_info_routers_1 = __importDefault(require("./routes/customers_info.routers"));
const geo_zones_routers_1 = __importDefault(require("./routes/geo_zones.routers"));
const languages_routers_1 = __importDefault(require("./routes/languages.routers"));
const manufacturers_routers_1 = __importDefault(require("./routes/manufacturers.routers"));
const manufacturers_info_routers_1 = __importDefault(require("./routes/manufacturers_info.routers"));
const newsletters_routers_1 = __importDefault(require("./routes/newsletters.routers"));
const orders_routers_1 = __importDefault(require("./routes/orders.routers"));
const orders_products_routers_1 = __importDefault(require("./routes/orders_products.routers"));
const orders_products_attributes_routers_1 = __importDefault(require("./routes/orders_products_attributes.routers"));
const orders_products_download_routers_1 = __importDefault(require("./routes/orders_products_download.routers"));
const orders_status_routers_1 = __importDefault(require("./routes/orders_status.routers"));
const orders_status_history_routers_1 = __importDefault(require("./routes/orders_status_history.routers"));
const orders_total_routers_1 = __importDefault(require("./routes/orders_total.routers"));
const products_routers_1 = __importDefault(require("./routes/products.routers"));
const products_attributes_routers_1 = __importDefault(require("./routes/products_attributes.routers"));
const products_attributes_download_routers_1 = __importDefault(require("./routes/products_attributes_download.routers"));
const products_description_routers_1 = __importDefault(require("./routes/products_description.routers"));
const products_notifications_routers_1 = __importDefault(require("./routes/products_notifications.routers"));
const products_options_routers_1 = __importDefault(require("./routes/products_options.routers"));
const products_options_values_routers_1 = __importDefault(require("./routes/products_options_values.routers"));
const products_options_values_to_products_options_routers_1 = __importDefault(require("./routes/products_options_values_to_products_options.routers"));
const products_to_categories_routers_1 = __importDefault(require("./routes/products_to_categories.routers"));
const reviews_routers_1 = __importDefault(require("./routes/reviews.routers"));
const reviews_description_routers_1 = __importDefault(require("./routes/reviews_description.routers"));
const sessions_routers_1 = __importDefault(require("./routes/sessions.routers"));
const specials_routers_1 = __importDefault(require("./routes/specials.routers"));
const tax_class_routers_1 = __importDefault(require("./routes/tax_class.routers"));
const tax_rates_routers_1 = __importDefault(require("./routes/tax_rates.routers"));
const whos_online_routers_1 = __importDefault(require("./routes/whos_online.routers"));
const zones_routers_1 = __importDefault(require("./routes/zones.routers"));
const zones_to_geo_zones_routers_1 = __importDefault(require("./routes/zones_to_geo_zones.routers"));
//login
const auth_routers_1 = __importDefault(require("./routes/auth.routers"));
app.use(auth_routers_1.default);
//lng
const lngs_routers_1 = __importDefault(require("./routes/lngs.routers"));
app.use(lngs_routers_1.default);
//uploadfile 
const uploadfileexpress_routers_1 = __importDefault(require("./routes/uploadfileexpress.routers"));
app.use(uploadfileexpress_routers_1.default);
//uploadfilemulter.routers
const uploadfilemulter_routers_1 = __importDefault(require("./routes/uploadfilemulter.routers"));
app.use(uploadfilemulter_routers_1.default);
// app.use('/uploads' , express.static('uploads'));
// app.use(express.static('uploads'));
app.use(index_routes_1.default, a_routers_1.default, address_book_routers_1.default, address_format_routers_1.default, administrators_routers_1.default, banners_routers_1.default, banners_history_routers_1.default, categories_routers_1.default, categories_description_routers_1.default, configuration_routers_1.default, configuration_group_routers_1.default, counter_routers_1.default, counter_history_routers_1.default, countries_routers_1.default, currencies_routers_1.default, customers_routers_1.default, customers_basket_routers_1.default, customers_basket_attributes_routers_1.default, customers_info_routers_1.default, geo_zones_routers_1.default, languages_routers_1.default, manufacturers_routers_1.default, manufacturers_info_routers_1.default, newsletters_routers_1.default, orders_routers_1.default, orders_products_routers_1.default, orders_products_attributes_routers_1.default, orders_products_download_routers_1.default, orders_status_routers_1.default, orders_status_history_routers_1.default, orders_total_routers_1.default, products_routers_1.default, products_attributes_routers_1.default, products_attributes_download_routers_1.default, products_description_routers_1.default, products_notifications_routers_1.default, products_options_routers_1.default, products_options_values_routers_1.default, products_options_values_to_products_options_routers_1.default, products_to_categories_routers_1.default, reviews_routers_1.default, reviews_description_routers_1.default, sessions_routers_1.default, specials_routers_1.default, tax_class_routers_1.default, tax_rates_routers_1.default, whos_online_routers_1.default, zones_routers_1.default, zones_to_geo_zones_routers_1.default);
exports.default = app;
